services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "6969:6969"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=posts_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - "27017:27017"
  # model:
  #   build: .
  #   command: uvicorn alpaca_api_waypoint:app --host 0.0.0.0 --port 8100
  #   volumes:
  #     - .:/alpaca_api_waypoint
  #   ports:
  #     - "8100:8100"